name: econ_site
services:
  db:
    image: "postgres:17.2-bookworm"
    container_name: ecom_db
    ports:
      - "$DB_PORT:5432"
    environment:
      POSTGRES_DB: $DB_NAME
      POSTGRES_HOST_AUTH_METHOD: "trust"
      POSTGRES_USER: $DB_USER
      DATABASE_PASSWORD: $DB_PASSWORD
    volumes:
      - data:/var/lib/postgresql@15/data
volumes:
  data:
